name: Conditions Data Extraction
description: >
  Template for conditions data extraction tasks as part of data harmonization in the INCLUDE DCC's Data Management Core (DMC). 
title: "[Study] [Version]: Conditions Data Extraction"
labels: []
projects: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Conditions Data Extraction
        ### Description: 
        This task involves extracting conditions data from original study tables. 
  - type: checkboxes
    attributes:
      label: Completion Checklist
      options:
        - label: Conditions Data Extracted
        - label: Data handed off for Annotation
  - type: input
    attributes: 
      label: Additional Notes 
      description: Add any relevant context or known issues that need extra attention. 
      placeholder: 'e.g., Select x was dropped ...'
